### ISSUE TITLE
Example in Docs fails 

### ISSUE THREAD

**Issue by tbrooke** [accordproject/concerto#421]
The documentation at https://docs.accordproject.org/docs/model-api.html has an example 

```

const ModelManager = require('@accordproject/concerto-core').ModelManager;
const Concerto = require('@accordproject/concerto-core').Concerto;
const modelManager = new ModelManager();
modelManager.addModelFile( `namespace org.acme.address
concept PostalAddress {
  o String streetAddress optional
  o String postalCode optional
  o String postOfficeBoxNumber optional
  o String addressRegion optional
  o String addressLocality optional
  o String addressCountry optional
}`, 'model.cto');

const postalAddress = {
    $class : 'org.acme.address.PostalAddress',
    streetAddress : '1 Maine Street'
};
const concerto = new Concerto(modelManager);
concerto.validate(postalAddress);
```

## Expected Behavior

```
const postalAddress = {
    $class : 'org.acme.address.PostalAddress',
    missing : '1 Maine Street'
};
```
## Current Behavior
```
/Users/tmb/Coding/Accord/nbb-concerto/node_modules/@accordproject/concerto-core/lib/basemodelmanager.js:168
        if (!this.modelFiles[modelFile.getNamespace()]) {
                                       ^
TypeError: modelFile.getNamespace is not a function
    at ModelManager.addModelFile (/Users/tmb/Coding/Accord/nbb-concerto/node_modules/@accordproject/concerto-core/lib/basemodelmanager.js:168:40)
    at Object.<anonymous> (/Users/tmb/Coding/Accord/nbb-concerto/test.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```
## Steps to Reproduce

1. Save example to file called test.js
2. run node test.js
3.
4.

### Desktop

  macOS]

**Comment by dselman** [comment]
The example should use `addCTOModel` instead of `addModelFile`. I will update...
