### ISSUE TITLE
Improve error reporting when decorator manager applies a duplicate decorator

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#711]
# Feature Request 🛍️

If a decorator command set APPENDS two decorators with the same name the resulting model is invalid.

## Use Case

Improve error reporting.

## Possible Solution

Fail-fast, when the decorator is being added, with a clearer error message.

## Context

Apply this decorator command twice to the model.

```
      {
        "$class": "org.accordproject.decoratorcommands@0.2.0.Command",
        "type": "APPEND",
        "target": {
          "$class": "org.accordproject.decoratorcommands@0.2.0.CommandTarget",
          "namespace": "test@1.0.0",
          "declaration": "Driver",
          "property": "favoriteColor" // if you change this to 'foo' then validateCommands will throw an error
        },
        "decorator": {
          "$class": "concerto.metamodel@1.0.0.Decorator",
          "name": "Preference",
          "arguments": []
        }
      }
```

Currently the error is detected when the new model is created, rather than when it is decorated.

```
IllegalModelException: Duplicate decorator Preference Line 11 column 3, to line 12 column 1. 
    at Field.validate (/home/runner/AccordProjectConcerto-Decorator-Command-Set/node_modules/@accordproject/concerto-core/lib/introspect/decorated.js:130:23)
    at Field.validate (/home/runner/AccordProjectConcerto-Decorator-Command-Set/node_modules/@accordproject/concerto-core/lib/introspect/property.js:139:15)
    at ConceptDeclaration.validate (/home/runner/AccordProjectConcerto-Decorator-Command-Set/node_modules/@accordproject/concerto-core/lib/introspect/classdeclaration.js:283:23)
    at ModelFile.validate (/home/runner/AccordProjectConcerto-Decorator-Command-Set/node_modules/@accordproject/concerto-core/lib/introspect/modelfile.js:279:30)
    at ModelManager.validateModelFiles (/home/runner/AccordProjectConcerto-Decorator-Command-Set/node_modules/@accordproject/concerto-core/lib/basemodelmanager.js:397:33)
    at ModelManager.fromAst (/home/runner/AccordProjectConcerto-Decorator-Command-Set/node_modules/@accordproject/concerto-core/lib/basemodelmanager.js:754:14)
    at Function.decorateModels (/home/runner/AccordProjectConcerto-Decorator-Command-Set/node_modules/@accordproject/concerto-core/lib/decoratormanager.js:115:25)
    at Object.<anonymous> (/home/runner/AccordProjectConcerto-Decorator-Command-Set/index.js:109:44)
```

**Comment by vr-varad** [comment]
hey @dselman ,I would like to work on this issue could u assign me this issue?

**Comment by subhajit20** [comment]
Hey @dselman can you review my pr?
And can I also get assigned?
