### ISSUE TITLE
Concerto CLI parser allows multiple application of the same Decorator, but not ModelManager

### ISSUE THREAD

**Issue by ekarademir** [accordproject/concerto#748]
# Bug Report 🐛
When the same decorator is applied to a property of a concept twice, we are getting different responses when parsed with concerto CLI and when CTO is added to the `ModelManager`, where `ModelManager` throws an error, but CLI tool is happy out.

## Expected Behavior
Either `ModelManager` shouldn't throw an error, or Concerto CLI should reject the file.

## Current Behavior
`ModelManager` throws an error, but concerto CLI doesn't.

## Steps to Reproduce
Given this CTO file
```csharp
namespace com.example.unit@1.0.0

concept FirstName
{
    @Term("a")
    @Term("b")
    o String value
}
```
running 
```bash
concerto parse --model com.example.unit.cto --output com.example.unit.json --excludeLineLocations
```
results in a successful parse, but the `ModelManager` throws 
```
IllegalModelException: Duplicate decorator Term Line 6 column 9, to line 9 column 5.

       6 | function makeModelFile(sources: string[], namespace: string): ModelFile {
       7 |   const modelManager = new ModelManager({ strict: true, regExp: RE2 });
    >  8 |   sources.forEach(source => modelManager.addCTOModel(source));
         |                                          ^
       9 |   return modelManager.getModelFile(namespace);
      10 | }
      11 |

      at Field.validate (node_modules/@accordproject/concerto-core/lib/introspect/decorated.js:130:23)
      at Field.validate (node_modules/@accordproject/concerto-core/lib/introspect/property.js:139:15)
      at ConceptDeclaration.validate (node_modules/@accordproject/concerto-core/lib/introspect/classdeclaration.js:283:23)
      at ModelFile.validate (node_modules/@accordproject/concerto-core/lib/introspect/modelfile.js:279:30)
      at ModelManager.addModelFile (node_modules/@accordproject/concerto-core/lib/basemodelmanager.js:224:27)
      at ModelManager.addModel (node_modules/@accordproject/concerto-core/lib/basemodelmanager.js:294:14)
      at ModelManager.addCTOModel (node_modules/@accordproject/concerto-core/lib/modelmanager.js:81:21)
      at src/util/model-compare.spec.ts:8:42
          at Array.forEach (<anonymous>)
      at makeModelFile (src/util/model-compare.spec.ts:8:11)
      at Object.<anonymous> (src/util/model-compare.spec.ts:322:25)
```

### Desktop
 - OS: macOs Ventura 13.6.1 (22G313)
 - Browser: Node v18.18.2
 - Version: Concerto v3.14.0

**Comment by ekarademir** [comment]
We decided to clarify the documentation. Since this is the expected way the parser works, i.e. parser only does syntactic validation but not semantic validation.
